/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126303-g9f35e220ff-20260827"
#endif /* AVUTIL_FFVERSION_H */
